#script for auto help
registerEvent player, 'chat', (event) ->
	msg = event.getMessage().toLowerCase()
	if msg.contains("how") && msg.contains("money") && msg.contains("?")
		event.setCancelled(true)
		event.player.sendMessage("You can get money by killing MOBs (the evil things in the night), animals, or players!")
		event.player.sendMessage("You can deposit the money into your account by finding a bank sign that says:")
		event.player.sendMessage("[Bank]")
		event.player.sendMessage("Deposit")
		event.player.sendMessage("All")
	if msg.contains("what") && msg.contains("is") && msg.contains("site") && msg.contains("?")
		event.setCancelled(true)
		event.player.sendMessage("\xA72The website is \xA73www.blackpulse.us\xA72! Be sure to stop by if you have any questions.")
	if msg.contains("is") && msg.contains("a") && msg.contains("admin") && msg.contains("on") && msg.contains("on") && msg.contains("?")
		event.setCancelled(true)
		event.player.sendMessage("\xA7cIf you need an admin or mod, please visit the website and request for one or join our ventrillo channel.")
	if msg.contains("where") && msg.contains("is") && msg.contains("bank") && msg.contains("?")
		event.setCancelled(true)
		event.player.sendMessage("\xA7aThe bank is located in Unity. You can get there by /warp bank or by going to spawn.")
	if msg.contains("this") && msg.contains("server") && (msg.contains("suck") || msg.contains("sux") || msg.contains("crap") || msg.contains("blows") || msg.contains("horrible"))
		event.setMessage("This server is great! I'm going to tell all my friends!")