// Generated by CoffeeScript 1.6.3
(function() {
  String.prop('reloadPlugin', {
    get: function() {
      return function() {
        bukkit.server.pluginManager.disablePlugin(this.plugin);
        bukkit.server.pluginManager.disablePlugin(this.plugin);
        return yes;
      };
    }
  });

}).call(this);
